_format_version: "1.1"

services:
  - name: auth-v1-open
    url: http://auth:9999/
    routes:
      - name: auth-v1-open
        strip_path: true
        paths:
          - /auth/v1/settings
          - /auth/v1/signout
          - /auth/v1/health
    plugins:
      - name: cors

  - name: auth-v1-open-s0
    url: http://auth:9999/
    routes:
      - name: auth-v1-open-s0
        strip_path: true
        paths:
          - /auth/v1/signup
          - /auth/v1/token
          - /auth/v1/verify
          - /auth/v1/recover
          - /auth/v1/resend
          - /auth/v1/logout
          - /auth/v1/magiclink
          - /auth/v1/user
          - /auth/v1/callback
          - /auth/v1/authorize
    plugins:
      - name: cors

  - name: auth-v1
    url: http://auth:9999/
    routes:
      - name: auth-v1-all
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false

  - name: rest-v1
    url: http://rest:3000/
    routes:
      - name: rest-v1-all
        strip_path: true
        paths:
          - /rest/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false

  - name: storage-v1
    url: http://storage:5000/
    routes:
      - name: storage-v1-all
        strip_path: true
        paths:
          - /storage/v1/
    plugins:
      - name: cors

  - name: functions-v1
    url: http://functions:9998/
    routes:
      - name: functions-v1-all
        strip_path: true
        paths:
          - /functions/v1/
    plugins:
      - name: cors

consumers:
  - username: anon
    keyauth_credentials:
      - key: ${ANON_KEY}
  - username: service_role
    keyauth_credentials:
      - key: ${SERVICE_ROLE_KEY}

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Language
        - Content-Language
        - Content-Type
        - Authorization
        - Cache-Control
        - Expires
        - Last-Modified
        - Pragma
        - apikey
        - x-client-info
      exposed_headers:
        - X-Total-Count
      credentials: true
      max_age: 3600