-- Seed marketplace with real integration packages
INSERT INTO public.marketplace_packages (
  package_name,
  display_name,
  description,
  category,
  vendor_name,
  vendor_email,
  package_version,
  min_halo_version,
  package_config,
  installation_config,
  pricing_model,
  price_per_month,
  is_verified,
  is_active,
  download_count,
  rating,
  rating_count,
  tags,
  screenshots,
  documentation_url,
  support_url,
  changelog
) VALUES 
-- Salesforce Integration
(
  'salesforce-connector',
  'Salesforce CRM Integration',
  'Connect to Salesforce CRM for lead management, opportunity tracking, and data synchronization',
  'crm',
  'HALO Official',
  'support@halo.dev',
  '2.1.0',
  '1.0.0',
  '{"nodes": [{"id": "salesforce-create-lead", "name": "Create Lead", "type": "action"}, {"id": "salesforce-update-opportunity", "name": "Update Opportunity", "type": "action"}], "credentials": {"type": "oauth2", "scopes": ["api", "refresh_token"]}}',
  '{"requires_oauth": true, "setup_steps": ["Configure OAuth", "Set permissions", "Test connection"]}',
  'free',
  0,
  true,
  true,
  2847,
  4.8,
  156,
  ARRAY['salesforce', 'crm', 'leads', 'opportunities'],
  ARRAY['https://example.com/screenshot1.png'],
  'https://docs.halo.dev/salesforce',
  'https://support.halo.dev/salesforce',
  '[{"version": "2.1.0", "changes": ["Added opportunity tracking", "Improved error handling"]}]'
),
-- HubSpot Integration  
(
  'hubspot-connector',
  'HubSpot Marketing & CRM',
  'Integrate with HubSpot for marketing automation, contact management, and analytics',
  'crm',
  'HALO Official', 
  'support@halo.dev',
  '1.8.3',
  '1.0.0',
  '{"nodes": [{"id": "hubspot-create-contact", "name": "Create Contact", "type": "action"}, {"id": "hubspot-send-email", "name": "Send Email", "type": "action"}], "credentials": {"type": "api_key", "fields": ["api_key"]}}',
  '{"requires_api_key": true, "setup_steps": ["Get API key", "Configure webhooks", "Test connection"]}',
  'free',
  0,
  true,
  true,
  1923,
  4.7,
  98,
  ARRAY['hubspot', 'marketing', 'crm', 'email'],
  ARRAY['https://example.com/hubspot1.png'],
  'https://docs.halo.dev/hubspot',
  'https://support.halo.dev/hubspot',
  '[{"version": "1.8.3", "changes": ["Fixed webhook handling", "Added email templates"]}]'
),
-- Slack Integration
(
  'slack-connector',
  'Slack Team Communication',
  'Send messages, create channels, and manage Slack workspace automation',
  'communication',
  'HALO Official',
  'support@halo.dev',
  '3.0.1',
  '1.0.0',
  '{"nodes": [{"id": "slack-send-message", "name": "Send Message", "type": "action"}, {"id": "slack-create-channel", "name": "Create Channel", "type": "action"}], "credentials": {"type": "oauth2", "scopes": ["chat:write", "channels:manage"]}}',
  '{"requires_oauth": true, "setup_steps": ["Install Slack app", "Authorize permissions", "Test message"]}',
  'free',
  0,
  true,
  true,
  4156,
  4.9,
  231,
  ARRAY['slack', 'communication', 'messaging', 'teams'],
  ARRAY['https://example.com/slack1.png'],
  'https://docs.halo.dev/slack',
  'https://support.halo.dev/slack',
  '[{"version": "3.0.1", "changes": ["Added thread support", "Improved file uploads"]}]'
),
-- Gmail Integration
(
  'gmail-connector',
  'Gmail Email Automation',
  'Send emails, manage labels, and automate Gmail workflows with advanced filtering',
  'email',
  'HALO Official',
  'support@halo.dev',
  '2.5.0',
  '1.0.0',
  '{"nodes": [{"id": "gmail-send-email", "name": "Send Email", "type": "action"}, {"id": "gmail-read-emails", "name": "Read Emails", "type": "trigger"}], "credentials": {"type": "oauth2", "scopes": ["https://www.googleapis.com/auth/gmail.modify"]}}',
  '{"requires_oauth": true, "setup_steps": ["Enable Gmail API", "Configure OAuth", "Set up filters"]}',
  'free',
  0,
  true,
  true,
  3421,
  4.6,
  187,
  ARRAY['gmail', 'email', 'google', 'automation'],
  ARRAY['https://example.com/gmail1.png'],
  'https://docs.halo.dev/gmail',
  'https://support.halo.dev/gmail',
  '[{"version": "2.5.0", "changes": ["Added attachment support", "Improved label management"]}]'
),
-- OpenAI Integration
(
  'openai-connector',
  'OpenAI GPT Integration',
  'Integrate OpenAI GPT models for text generation, analysis, and AI-powered automation',
  'ai',
  'HALO Official',
  'support@halo.dev',
  '1.4.2',
  '1.0.0',
  '{"nodes": [{"id": "openai-generate-text", "name": "Generate Text", "type": "action"}, {"id": "openai-analyze-text", "name": "Analyze Text", "type": "action"}], "credentials": {"type": "api_key", "fields": ["api_key"]}}',
  '{"requires_api_key": true, "setup_steps": ["Get OpenAI API key", "Configure model settings", "Test generation"]}',
  'premium',
  19.99,
  true,
  true,
  1654,
  4.8,
  89,
  ARRAY['openai', 'ai', 'gpt', 'text-generation'],
  ARRAY['https://example.com/openai1.png'],
  'https://docs.halo.dev/openai',
  'https://support.halo.dev/openai',
  '[{"version": "1.4.2", "changes": ["Added GPT-4 support", "Improved token management"]}]'
),
-- Webhook Integration
(
  'webhook-connector',
  'Webhook Triggers & Actions',
  'Create webhook endpoints and send HTTP requests to external services',
  'webhook',
  'HALO Official',
  'support@halo.dev',
  '2.0.0',
  '1.0.0',
  '{"nodes": [{"id": "webhook-trigger", "name": "Webhook Trigger", "type": "trigger"}, {"id": "http-request", "name": "HTTP Request", "type": "action"}], "credentials": {"type": "none"}}',
  '{"requires_setup": false, "setup_steps": ["Configure endpoint", "Set authentication", "Test webhook"]}',
  'free',
  0,
  true,
  true,
  5234,
  4.5,
  298,
  ARRAY['webhook', 'http', 'api', 'integration'],
  ARRAY['https://example.com/webhook1.png'],
  'https://docs.halo.dev/webhook',
  'https://support.halo.dev/webhook',
  '[{"version": "2.0.0", "changes": ["Added authentication methods", "Improved error handling"]}]'
),
-- Database Integration
(
  'database-connector',
  'Database Operations',
  'Connect to PostgreSQL, MySQL, and other databases for data operations',
  'database',
  'HALO Official',
  'support@halo.dev',
  '1.6.1',
  '1.0.0',
  '{"nodes": [{"id": "db-query", "name": "Execute Query", "type": "action"}, {"id": "db-insert", "name": "Insert Data", "type": "action"}], "credentials": {"type": "connection_string", "fields": ["host", "port", "database", "username", "password"]}}',
  '{"requires_credentials": true, "setup_steps": ["Configure connection", "Test database access", "Set up queries"]}',
  'premium',
  29.99,
  true,
  true,
  987,
  4.4,
  45,
  ARRAY['database', 'postgresql', 'mysql', 'data'],
  ARRAY['https://example.com/db1.png'],
  'https://docs.halo.dev/database',
  'https://support.halo.dev/database',
  '[{"version": "1.6.1", "changes": ["Added MySQL support", "Improved connection pooling"]}]'
),
-- File Storage Integration
(
  'file-storage-connector',
  'File Storage & Processing',
  'Upload, download, and process files with cloud storage providers',
  'storage',
  'HALO Official',
  'support@halo.dev',
  '1.3.0',
  '1.0.0',
  '{"nodes": [{"id": "file-upload", "name": "Upload File", "type": "action"}, {"id": "file-process", "name": "Process File", "type": "action"}], "credentials": {"type": "api_key", "fields": ["access_key", "secret_key"]}}',
  '{"requires_credentials": true, "setup_steps": ["Configure storage provider", "Set up bucket", "Test upload"]}',
  'premium',
  14.99,
  true,
  true,
  765,
  4.3,
  34,
  ARRAY['storage', 'files', 'cloud', 'upload'],
  ARRAY['https://example.com/storage1.png'],
  'https://docs.halo.dev/storage',
  'https://support.halo.dev/storage',
  '[{"version": "1.3.0", "changes": ["Added batch processing", "Improved error handling"]}]'
);